
name: pitest-on-master

on:
  push:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/checkout@v2
        with:
          java-version: 1.11

      - name: Maven build
        run: mvn clean package

      - name: Run Mutation Testing
        run: mvn package -Ppitest org.pitest:pitest-maven:mutationCoverage

      - name: Slack notification
          env:
            SLACK_USERNAME: GITHUB ACTION BOT
            SLACK_COLOR: green
            SLACK_MESSAGE: 'Un push vient d avoir lieu'
            SLACK_TITLE: Nouveau Push

            SLACK_CHANNEL: si3-qgl-20-21-les_qualituriers
            SLACK_WEBHOOK: https://hooks.slack.com/services/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


          uses: Ilshidur/action-slack@2.0.2
          with:
            args: 'A new commit has been pushed.'
