name: Pull-Request

# Trigger de déclenchement de cette action
on: pull-request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/checkout@v2
        with:
          java-version: 1.11

      - name: Maven build
        run: mvn clean package





